apiVersion: v2
name: datahub-executor-worker
description: A Helm chart for datahub-executor-worker
type: application
version: 0.0.36
appVersion: 0.3.17.3
maintainers:
  - name: DataHub
    email: datahub@acryl.io
